version: 1.0.{build}

branches:
  only:
  - rxui7-master

environment:
  ANDROID_HOME: "C:\\android-sdk-windows"

  COVERALLS_TOKEN:
    secure: NVBDhKKddMUzMSpWusjy5kUhomQYuRORrWtULtVcrgp0W9Ih4dueqQVp1mnkewA8

  NUGET_SOURCE: https://www.myget.org/F/reactiveui/api/v2/package
  NUGET_APIKEY:
    secure: YP/3KxC2ffsuHNaolPXj66JVGzSjON9FcR2S2OEzn9c6SV14oPzUh1ySyeT+G+aA

xamarin:
  email: ghuntley@ghuntley.com
  password:
    secure: 9PLfbvP3ON+Xk17Yd4rJag==
  android: true
  ios: true

init:
  - cd \
  - appveyor DownloadFile http://dl.google.com/android/android-sdk_r24.4.1-windows.zip
  - 7z x android-sdk_r24.4.1-windows.zip > nul
  - cd "C:\projects\reactiveui"

install: 

  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-24.0.2
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-24
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-google-m2repository
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-android-m2repository

build_script:
- ps: >-

    ./build.cmd

test: off

artifacts:
  - path: '**/bin/*'
  - path: src/ReactiveUI.Events/Events_*.cs
  - path: artifacts/*


on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))