//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("ReactiveUI")]
[assembly: AssemblyVersion("7.0.2")]
[assembly: AssemblyFileVersion("7.0.2")]
[assembly: AssemblyInformationalVersion("7.0.2+488.Branch.chillisource.Sha.8c332d7ef5c2ca3f551eded16861a222c8913e0c")]
[assembly: AssemblyCopyright("Copyright (c) ReactiveUI and contributors")]

