//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("ReactiveUI")]
[assembly: AssemblyVersion("7.2.1")]
[assembly: AssemblyFileVersion("7.2.1")]
[assembly: AssemblyInformationalVersion("7.2.1+13.Branch.chillisource.Sha.65daa56a19a04b80ace6cc25fe243de2d001e4e6")]
[assembly: AssemblyCopyright("Copyright (c) ReactiveUI and contributors")]

